### ISSUE TITLE
update 1，更新接口的连接貌似挂了？

### ISSUE THREAD

**Issue by untitan** [SuperLinkStudio/SMSboom-HXCZ#3]
update 1，更新接口的连接貌似挂了？

**Comment by Starry-Sky-World** [comment]
选SuperLinkStudioCloud，确保网络能连接Github
实在不行手动在仓库下载，仓库是正常的

**Comment by Starry-Sky-World** [comment]
实在不行发Email问我：liu_qinyu@outlook.com
