### ISSUE TITLE
接口更新地址没了

### ISSUE THREAD

**Issue by KeduLee** [SuperLinkStudio/SMSboom-HXCZ#9]
有新的短信接口吗，接口更新地址没了，404

**Comment by Starry-Sky-World** [comment]
嘶...知道了，马上处理

**Comment by KeduLee** [comment]
![屏幕截图 2024-07-24 124515](https://github.com/user-attachments/assets/a294b350-78d5-4ea1-b231-83d342a8d68d)
![image](https://github.com/user-attachments/assets/9bc78850-bc13-4c7b-b51c-59fa373458f2)
新增的apiS接口也挂了
